version: "3.3"

services:

  zookeeper:
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "32181:32181"
    deploy:
      replicas: 1

  kafka:
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.99.100:29092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092"
    deploy:
      replicas: 1
    depends_on:
      - zookeeper
